begin;
create extension if not exists pgtap with schema extensions;
set local search_path=extensions,public;
select no_plan();
create function pg_temp.u(n integer) returns uuid language sql immutable as $$ select ('a6100000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid $$;
create function pg_temp.c(n integer) returns uuid language sql immutable as $$ select ('a6200000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid $$;
insert into auth.users(id,email,email_confirmed_at) select pg_temp.u(n),'a4-negative-'||n||'@example.invalid',now() from generate_series(1,30)n;
insert into auth.mfa_factors(id,user_id,factor_type,status,secret,created_at,updated_at)
 select pg_temp.u(n),pg_temp.u(n),'totp','verified','SYNTHETICTEST',now(),now() from generate_series(1,30)n;
insert into auth.sessions(id,user_id,aal,factor_id,created_at,updated_at)
 select pg_temp.u(n),pg_temp.u(n),'aal2',pg_temp.u(n),clock_timestamp(),clock_timestamp() from generate_series(1,30)n;
insert into auth.mfa_amr_claims(id,session_id,authentication_method,created_at,updated_at)
 select gen_random_uuid(),pg_temp.u(n),case when n>=10 then 'recovery' else 'password' end,now(),now() from generate_series(1,30)n;
insert into private.account_recovery_grants(user_id) values(pg_temp.u(1)),(pg_temp.u(2));
insert into public.restaurants(id,slug,display_name) values(pg_temp.c(1),'a4-denials','Synthetic A4 denials');
insert into public.restaurant_memberships(restaurant_id,user_id,role,status)
 select pg_temp.c(1),pg_temp.u(n),role,'active' from (values(5,'owner'),(6,'manager'),(7,'kitchen'),(8,'driver'),(9,'viewer'))x(n,role);
insert into private.provide_admin_grants(user_id,restaurant_id) values(pg_temp.u(3),pg_temp.c(1)),(pg_temp.u(4),null);
insert into private.account_recovery_contacts(id,user_id,reference) select pg_temp.u(n),pg_temp.u(n),'prior-'||n from generate_series(10,30)n;
create function pg_temp.run(actor_n integer,case_n integer,action text,extra jsonb default '{}') returns jsonb
language plpgsql as $$ declare q jsonb;begin
 q:=jsonb_build_object('action',action,'caseId',pg_temp.c(case_n),'commandId',gen_random_uuid(),'expectedRevision',(select revision from private.account_recovery_cases where id=pg_temp.c(case_n)))||extra;
 return private.account_recovery_command(pg_temp.u(actor_n),pg_temp.u(actor_n),'aal2',q);
end $$;
create function pg_temp.approved(n integer) returns void language plpgsql as $$ begin
 perform pg_temp.run(n,n,'request','{"kind":"lost_factor","reason":"factor_lost"}');
 perform pg_temp.run(1,n,'verify',jsonb_build_object('contactId',pg_temp.u(n),'evidenceReference','independent-proof'));
 perform pg_temp.run(1,n,'approve');
end $$;
select pg_temp.approved(10);
select is(pg_temp.run(n,10,'read')->>'outcome','forbidden','role/platform without explicit global recovery grant: actor '||n) from generate_series(3,9)n;
update auth.users set banned_until=now()+interval '1 hour' where id=pg_temp.u(1);
select is(pg_temp.run(1,10,'execute')->>'outcome','forbidden','banned operator cannot execute');
update auth.users set banned_until=null where id=pg_temp.u(1);
update private.account_security_state set blocked=true where user_id=pg_temp.u(1);
select is(pg_temp.run(1,10,'execute')->>'outcome','forbidden','suspended operator cannot execute');
update private.account_security_state set blocked=false where user_id=pg_temp.u(1);
update auth.sessions set aal='aal1' where id=pg_temp.u(1);
select is(private.account_recovery_command(pg_temp.u(1),pg_temp.u(1),'aal1',jsonb_build_object('action','execute','caseId',pg_temp.c(10),'commandId',gen_random_uuid(),'expectedRevision',3))->>'outcome','forbidden','aal1 operator cannot execute');
update auth.sessions set aal='aal2' where id=pg_temp.u(1);
update private.account_recovery_grants set active=false where user_id=pg_temp.u(1);
select is(pg_temp.run(1,10,'execute')->>'outcome','forbidden','revoked recovery grant cannot execute');
update private.account_recovery_grants set active=true where user_id=pg_temp.u(1);
select is(pg_temp.run(1,10,'execute')->>'outcome','forbidden','regrant cannot revive prior approval');
select pg_temp.approved(11);
update private.account_recovery_cases set approval_expires_at=clock_timestamp()-interval '1 second' where id=pg_temp.c(11);
select is(pg_temp.run(1,11,'execute')->>'outcome','conflict','expired 15 minute approval cannot execute');
select ok(not (select blocked from private.account_security_state where user_id=pg_temp.u(11)),'expired approval does not lock target');
select pg_temp.approved(12);
update auth.users set email='changed-a4@example.invalid' where id=pg_temp.u(12);
select is(pg_temp.run(1,12,'execute')->>'outcome','conflict','changed target email invalidates approval');
select pg_temp.approved(13);
update auth.mfa_factors set updated_at=clock_timestamp() where user_id=pg_temp.u(13);
select is(pg_temp.run(1,13,'execute')->>'outcome','conflict','changed target factor invalidates approval');
select pg_temp.approved(14);
insert into private.provide_admin_grants(user_id) values(pg_temp.u(14));
select is(pg_temp.run(1,14,'execute')->>'outcome','conflict','changed platform rights invalidate approval');
select pg_temp.approved(15);
select is(pg_temp.run(15,15,'cancel')->'data'->>'state','cancelled','target can withdraw before effect');
select is(pg_temp.run(1,15,'execute')->>'outcome','conflict','withdrawn case cannot execute');
select pg_temp.approved(16);
select is(pg_temp.run(1,16,'execute')->'data'->>'state','executing','ordinary identity requires one independent operator');
select is(private.finish_account_recovery_effect(pg_temp.u(1),pg_temp.u(1),'aal2',pg_temp.c(16),gen_random_uuid(),false)->'data'->>'state','executing','concurrent replay waits for in-flight effect without blind retry');
select is(private.finish_account_recovery_effect(pg_temp.u(1),pg_temp.u(1),'aal2',pg_temp.c(16),gen_random_uuid(),true)->'data'->>'state','needs_review','finished but uncertain effect requires review');
select ok((select blocked and needs_review from private.account_security_state where user_id=pg_temp.u(16)),'uncertain provider effect remains blocked');
select pg_temp.approved(17);
select is(pg_temp.run(1,17,'execute')->'data'->>'state','executing','another bounded effect begins');
update private.account_recovery_cases set expires_at=clock_timestamp()-interval '1 second' where id=pg_temp.c(17);
select is(private.finish_account_recovery_effect(pg_temp.u(1),pg_temp.u(1),'aal2',pg_temp.c(17),gen_random_uuid(),true)->'data'->>'state','needs_review','expiration after intent requires review');
select ok((select blocked from private.account_security_state where user_id=pg_temp.u(17)),'deadline cannot unlock an executing case');
select is(pg_temp.run(5,25,'request',jsonb_build_object('kind','replace_factor','reason','factor_replaced','oldFactorId',pg_temp.u(6)))->>'outcome','forbidden','foreign old factor is rejected');
select is(pg_temp.run(5,25,'request',jsonb_build_object('kind','replace_factor','reason','factor_replaced','oldFactorId',pg_temp.u(5)))->>'outcome','allowed','replacement first binds current old MFA');
insert into auth.mfa_factors(id,user_id,factor_type,status,secret,created_at,updated_at) values(pg_temp.u(55),pg_temp.u(5),'totp','unverified','SYNTHETICTEST',clock_timestamp(),clock_timestamp());
select is(pg_temp.run(5,25,'begin_replacement',jsonb_build_object('newFactorId',pg_temp.u(55)))->>'outcome','forbidden','unverified replacement cannot remove last factor');
select ok(exists(select 1 from auth.mfa_factors where id=pg_temp.u(5)),'old verified factor remains present');
select is(pg_temp.run(6,26,'request','{"kind":"password","reason":"forgot_password"}')->>'outcome','forbidden','normal or invitation-like session is not recovery purpose');
select ok(not private.account_session_live(pg_temp.u(18),pg_temp.u(18)::text,'aal2'),'even aal2 recovery-purpose session cannot enter business paths');
select set_config('request.jwt.claims',jsonb_build_object('sub',pg_temp.u(5),'aal','aal2','session_id',pg_temp.u(5))::text,true);
select ok(private.is_restaurant_member(pg_temp.c(1)),'direct member helper accepts live self');
update private.account_security_state set blocked=true where user_id=pg_temp.u(5);
select ok(not private.is_restaurant_member(pg_temp.c(1)),'direct member helper cannot bypass account block');
select ok(not private.has_restaurant_role(pg_temp.c(1),array['owner']),'direct role helper cannot bypass account block');
select ok(not has_function_privilege('authenticated','private.is_restaurant_member_before_account_session(uuid)','execute'),'legacy member helper has no browser execute');
select ok(not has_function_privilege('authenticated','private.has_restaurant_role_before_account_session(uuid,text[])','execute'),'legacy role helper has no browser execute');
select ok(not has_function_privilege('authenticated','private.account_recovery_command(uuid,uuid,text,jsonb)','execute'),'no new direct browser recovery RPC');
select ok(not has_table_privilege('authenticated','private.account_recovery_contacts','select'),'no browser proof/contact directory');
select ok(not has_table_privilege('authenticated','private.account_recovery_audit','select'),'no browser immutable-audit directory');
select * from finish();
rollback;
